import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/batch.dart';
import '../models/student.dart';
import '../models/user.dart';

class AttendancePdfGenerator {
  static final DateFormat _df = DateFormat('dd MMM yyyy');
  static final DateFormat _dtf = DateFormat('dd MMM yyyy, hh:mm a');

  static String _formatRange(DateTime from, DateTime to) {
    if (from.year == to.year && from.month == to.month && from.day == to.day) {
      return _df.format(from);
    }
    return '${_df.format(from)} — ${_df.format(to)}';
  }

  static pw.Widget _buildHeader({
    required String maktabName,
    required String reportTitle,
    required DateTime fromDate,
    required DateTime toDate,
  }) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          maktabName,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.teal900),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          reportTitle,
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColors.black),
        ),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Date Range: ${_formatRange(fromDate, toDate)}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
            pw.Text(
              'Generated: ${_dtf.format(DateTime.now())}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ],
        ),
        pw.SizedBox(height: 4),
        pw.Divider(thickness: 1, color: PdfColors.teal800),
        pw.SizedBox(height: 8),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context, String senderName) {
    return pw.Column(
      children: [
        pw.Divider(thickness: 0.5, color: PdfColors.grey400),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by $senderName',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ],
        ),
      ],
    );
  }

  /// 1. Attendance Summary for All Batches
  static Future<Uint8List> buildAllBatchesReport({
    required String maktabName,
    required DateTime fromDate,
    required DateTime toDate,
    required List<Batch> batches,
    required Map<int, Map<String, int>> dataByBatch,
    required String senderName,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(
          maktabName: maktabName,
          reportTitle: 'All Batches Attendance Summary Report',
          fromDate: fromDate,
          toDate: toDate,
        ),
        footer: (context) => _buildFooter(context, senderName),
        build: (context) {
          int totalStudents = 0;
          int totalPresent = 0;
          int totalAbsent = 0;
          int totalLate = 0;
          int totalLeave = 0;

          final tableRows = <List<String>>[];

          for (final b in batches) {
            final stats = dataByBatch[b.id] ?? {};
            final stCount = stats['total'] ?? 0;
            final prCount = stats['present'] ?? 0;
            final abCount = stats['absent'] ?? 0;
            final ltCount = stats['late'] ?? 0;
            final lvCount = stats['leave'] ?? 0;
            final recCount = stats['total_records'] ?? (prCount + abCount + ltCount + lvCount);

            totalStudents += stCount;
            totalPresent += prCount;
            totalAbsent += abCount;
            totalLate += ltCount;
            totalLeave += lvCount;

            final pct = recCount > 0
                ? '${((prCount + ltCount) / recCount * 100).toStringAsFixed(1)}%'
                : '—';

            tableRows.add([
              b.name,
              b.timing,
              stCount.toString(),
              prCount.toString(),
              abCount.toString(),
              ltCount.toString(),
              lvCount.toString(),
              pct,
            ]);
          }

          final grandTotalRecords = totalPresent + totalAbsent + totalLate + totalLeave;
          final grandPct = grandTotalRecords > 0
              ? '${((totalPresent + totalLate) / grandTotalRecords * 100).toStringAsFixed(1)}%'
              : '—';

          return [
            pw.TableHelper.fromTextArray(
              headers: ['Batch', 'Timing', 'Students', 'Present', 'Absent', 'Late', 'Leave', 'Attendance %'],
              data: tableRows,
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.teal800),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                2: pw.Alignment.center,
                3: pw.Alignment.center,
                4: pw.Alignment.center,
                5: pw.Alignment.center,
                6: pw.Alignment.center,
                7: pw.Alignment.center,
              },
            ),
            pw.SizedBox(height: 16),
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.teal50,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: PdfColors.teal300, width: 0.8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  pw.Text('Total Students: $totalStudents', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                  pw.Text('Present: $totalPresent', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.green800)),
                  pw.Text('Absent: $totalAbsent', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.red800)),
                  pw.Text('Late: $totalLate', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.orange800)),
                  pw.Text('Overall Attendance: $grandPct', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.teal900)),
                ],
              ),
            ),
          ];
        },
      ),
    );

    return doc.save();
  }

  /// 2. Single Batch Attendance Report
  static Future<Uint8List> buildBatchReport({
    required String maktabName,
    required Batch batch,
    required DateTime fromDate,
    required DateTime toDate,
    required List<Map<String, dynamic>> rows,
    required String senderName,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(
          maktabName: maktabName,
          reportTitle: 'Batch Attendance Report — ${batch.name} (${batch.timing})',
          fromDate: fromDate,
          toDate: toDate,
        ),
        footer: (context) => _buildFooter(context, senderName),
        build: (context) {
          int totalPresent = 0;
          int totalAbsent = 0;
          int totalLate = 0;
          int totalLeave = 0;

          final tableRows = rows.map((r) {
            final pr = (r['present'] as num?)?.toInt() ?? 0;
            final ab = (r['absent'] as num?)?.toInt() ?? 0;
            final lt = (r['late'] as num?)?.toInt() ?? 0;
            final lv = (r['leave'] as num?)?.toInt() ?? 0;
            final totalMarked = (r['total_marked'] as num?)?.toInt() ?? (pr + ab + lt + lv);

            totalPresent += pr;
            totalAbsent += ab;
            totalLate += lt;
            totalLeave += lv;

            final pct = totalMarked > 0
                ? '${((pr + lt) / totalMarked * 100).toStringAsFixed(1)}%'
                : '—';

            return [
              r['student_name']?.toString() ?? '',
              r['admission_number']?.toString() ?? 'N/A',
              pr.toString(),
              ab.toString(),
              lt.toString(),
              lv.toString(),
              pct,
            ];
          }).toList();

          final grandTotal = totalPresent + totalAbsent + totalLate + totalLeave;
          final grandPct = grandTotal > 0
              ? '${((totalPresent + totalLate) / grandTotal * 100).toStringAsFixed(1)}%'
              : '—';

          return [
            pw.TableHelper.fromTextArray(
              headers: ['Student Name', 'Adm No.', 'Present', 'Absent', 'Late', 'Leave', 'Attendance %'],
              data: tableRows,
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.teal800),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                1: pw.Alignment.center,
                2: pw.Alignment.center,
                3: pw.Alignment.center,
                4: pw.Alignment.center,
                5: pw.Alignment.center,
                6: pw.Alignment.center,
              },
            ),
            pw.SizedBox(height: 16),
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.teal50,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: PdfColors.teal300, width: 0.8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  pw.Text('Students: ${rows.length}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                  pw.Text('Present: $totalPresent', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.green800)),
                  pw.Text('Absent: $totalAbsent', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.red800)),
                  pw.Text('Late: $totalLate', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.orange800)),
                  pw.Text('Batch Attendance: $grandPct', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.teal900)),
                ],
              ),
            ),
          ];
        },
      ),
    );

    return doc.save();
  }

  /// 3. Single Student Attendance Report
  static Future<Uint8List> buildStudentReport({
    required String maktabName,
    required Student student,
    required String batchName,
    required DateTime fromDate,
    required DateTime toDate,
    required List<Map<String, dynamic>> dailyRows,
    required String senderName,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(
          maktabName: maktabName,
          reportTitle: 'Student Individual Attendance Report',
          fromDate: fromDate,
          toDate: toDate,
        ),
        footer: (context) => _buildFooter(context, senderName),
        build: (context) {
          int presentCount = 0;
          int absentCount = 0;
          int lateCount = 0;
          int leaveCount = 0;

          final tableRows = dailyRows.map((r) {
            final status = (r['status'] ?? '').toString();
            final remarks = (r['remarks'] ?? '').toString();
            final date = (r['date'] ?? '').toString();

            if (status.toLowerCase() == 'present') {
              presentCount++;
            } else if (status.toLowerCase() == 'absent') {
              absentCount++;
            } else if (status.toLowerCase() == 'late') {
              lateCount++;
            } else if (status.toLowerCase() == 'leave') {
              leaveCount++;
            }

            return [
              date,
              status,
              remarks.isEmpty ? '—' : remarks,
            ];
          }).toList();

          final totalDays = dailyRows.length;
          final attPct = totalDays > 0
              ? '${((presentCount + lateCount) / totalDays * 100).toStringAsFixed(1)}%'
              : '—';

          return [
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: PdfColors.grey300),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Student: ${student.name}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
                      pw.SizedBox(height: 2),
                      pw.Text('Admission No: ${student.admissionNumber}', style: const pw.TextStyle(fontSize: 10)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Batch: $batchName', style: const pw.TextStyle(fontSize: 10)),
                      pw.SizedBox(height: 2),
                      pw.Text('Phone: ${student.phone ?? student.guardianPhone ?? 'N/A'}', style: const pw.TextStyle(fontSize: 10)),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 14),
            pw.TableHelper.fromTextArray(
              headers: ['Date', 'Status', 'Remarks'],
              data: tableRows,
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.teal800),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                0: pw.Alignment.center,
                1: pw.Alignment.center,
              },
            ),
            pw.SizedBox(height: 14),
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.teal50,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: PdfColors.teal300, width: 0.8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  pw.Text('Recorded Days: $totalDays', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                  pw.Text('Present: $presentCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.green800)),
                  pw.Text('Absent: $absentCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.red800)),
                  pw.Text('Late: $lateCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.orange800)),
                  pw.Text('Leave: $leaveCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.blue800)),
                  pw.Text('Attendance: $attPct', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.teal900)),
                ],
              ),
            ),
          ];
        },
      ),
    );

    return doc.save();
  }

  /// 4. Single Teacher Attendance Report
  static Future<Uint8List> buildTeacherReport({
    required String maktabName,
    required User teacher,
    required DateTime fromDate,
    required DateTime toDate,
    required List<Map<String, dynamic>> dailyRows,
    required String senderName,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(
          maktabName: maktabName,
          reportTitle: 'Teacher Attendance Report',
          fromDate: fromDate,
          toDate: toDate,
        ),
        footer: (context) => _buildFooter(context, senderName),
        build: (context) {
          int presentCount = 0;
          int absentCount = 0;
          int lateCount = 0;
          int leaveCount = 0;

          final tableRows = dailyRows.map((r) {
            final status = (r['status'] ?? '').toString();
            final remarks = (r['remarks'] ?? '').toString();
            final date = (r['date'] ?? '').toString();
            final time = (r['time'] ?? '').toString();

            if (status.toLowerCase() == 'present') {
              presentCount++;
            } else if (status.toLowerCase() == 'absent') {
              absentCount++;
            } else if (status.toLowerCase() == 'late') {
              lateCount++;
            } else if (status.toLowerCase() == 'leave') {
              leaveCount++;
            }

            return [
              date,
              status,
              time.isEmpty ? '—' : time,
              remarks.isEmpty ? '—' : remarks,
            ];
          }).toList();

          final totalDays = dailyRows.length;
          final attPct = totalDays > 0
              ? '${((presentCount + lateCount) / totalDays * 100).toStringAsFixed(1)}%'
              : '—';

          return [
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: PdfColors.grey300),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Teacher: ${teacher.name}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
                      pw.SizedBox(height: 2),
                      pw.Text('Teacher ID: ${teacher.teacherId ?? teacher.id ?? 'N/A'}', style: const pw.TextStyle(fontSize: 10)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Role: ${teacher.role}', style: const pw.TextStyle(fontSize: 10)),
                      pw.SizedBox(height: 2),
                      pw.Text('Mobile: ${teacher.mobile ?? 'N/A'}', style: const pw.TextStyle(fontSize: 10)),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 14),
            pw.TableHelper.fromTextArray(
              headers: ['Date', 'Status', 'Time', 'Remarks'],
              data: tableRows,
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.teal800),
              cellStyle: const pw.TextStyle(fontSize: 9),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                0: pw.Alignment.center,
                1: pw.Alignment.center,
                2: pw.Alignment.center,
              },
            ),
            pw.SizedBox(height: 14),
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.teal50,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: PdfColors.teal300, width: 0.8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  pw.Text('Recorded Days: $totalDays', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                  pw.Text('Present: $presentCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.green800)),
                  pw.Text('Absent: $absentCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.red800)),
                  pw.Text('Late: $lateCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.orange800)),
                  pw.Text('Leave: $leaveCount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.blue800)),
                  pw.Text('Attendance: $attPct', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10, color: PdfColors.teal900)),
                ],
              ),
            ),
          ];
        },
      ),
    );

    return doc.save();
  }
}
