class ReceiptTemplates {
  static const Map<String, Map<String, String>> _templates = {
    'en': {
      // Fee receipt
      'header': 'Maktab Management — Payment Receipt',
      'date': 'Date',
      'receivedBy': 'Received by',
      'student': 'Student',
      'amount': 'Amount',
      'mode': 'Mode',
      'notes': 'Notes',
      'total': 'Total',
      'footer': 'Jazak Allah Khair.',
      // Salary receipt
      'salaryHeader': 'Maktab Management — Salary Receipt',
      'salaryMonth': 'Month',
      'salaryPaidTo': 'Paid to',
      'salaryIssuedBy': 'Issued by',
      // Attendance
      'attendanceHeader': 'Maktab Management — Attendance Summary',
      'batch': 'Batch',
      'present': 'Present',
      'absent': 'Absent',
      'late': 'Late',
      'leave': 'Leave',
      'markedBy': 'Marked by',
      // Absent notification
      'absentHeader': 'Maktab Management — Absence Notice',
      'absentBody': 'Your child was marked ABSENT today.',
      'pleaseContact': 'Please contact the Maktab for details.',
      // Batch notice
      'batchNoticeHeader': 'Maktab Management — Batch Notice',
      'timing': 'Timing',
      // Generic announcement
      'announcementHeader': 'Maktab Management — Announcement',
    },
    'ur': {
      'header': 'مکتب مینجمنٹ — ادائیگی کی رسید',
      'date': 'تاریخ',
      'receivedBy': 'وصول کنندہ',
      'student': 'طالب علم',
      'amount': 'رقم',
      'mode': 'طریقہ',
      'notes': 'نوٹس',
      'total': 'کل',
      'footer': 'جزاک اللہ خیر۔',
      'salaryHeader': 'مکتب مینجمنٹ — تنخواہ کی رسید',
      'salaryMonth': 'مہینہ',
      'salaryPaidTo': 'ادا کیا گیا',
      'salaryIssuedBy': 'جاری کنندہ',
      'attendanceHeader': 'مکتب مینجمنٹ — حاضری کا خلاصہ',
      'batch': 'بیچ',
      'present': 'حاضر',
      'absent': 'غیر حاضر',
      'late': 'تاخیر',
      'leave': 'رخصت',
      'markedBy': 'نشان زد کرنے والا',
      'absentHeader': 'مکتب مینجمنٹ — غیر حاضری کی اطلاع',
      'absentBody': 'آپ کے بچے کو آج غیر حاضر نشان زد کیا گیا۔',
      'pleaseContact': 'تفصیلات کے لیے مکتب سے رابطہ کریں۔',
      'batchNoticeHeader': 'مکتب مینجمنٹ — بیچ نوٹس',
      'timing': 'وقت',
      'announcementHeader': 'مکتب مینجمنٹ — اعلان',
    },
    'hi': {
      'header': 'मकतब प्रबंधन — भुगतान रसीद',
      'date': 'तिथि',
      'receivedBy': 'प्राप्तकर्ता',
      'student': 'छात्र',
      'amount': 'राशि',
      'mode': 'माध्यम',
      'notes': 'टिप्पणी',
      'total': 'कुल',
      'footer': 'जज़ाक अल्लाह खैर।',
      'salaryHeader': 'मकतब प्रबंधन — वेतन रसीद',
      'salaryMonth': 'महीना',
      'salaryPaidTo': 'भुगतान किया',
      'salaryIssuedBy': 'जारीकर्ता',
      'attendanceHeader': 'मकतब प्रबंधन — उपस्थिति सारांश',
      'batch': 'बैच',
      'present': 'उपस्थित',
      'absent': 'अनुपस्थित',
      'late': 'देर',
      'leave': 'अवकाश',
      'markedBy': 'चिह्नित करने वाला',
      'absentHeader': 'मकतब प्रबंधन — अनुपस्थिति सूचना',
      'absentBody': 'आपके बच्चे को आज अनुपस्थित चिह्नित किया गया।',
      'pleaseContact': 'विवरण के लिए मकतब से संपर्क करें।',
      'batchNoticeHeader': 'मकतब प्रबंधन — बैच सूचना',
      'timing': 'समय',
      'announcementHeader': 'मकतब प्रबंधन — घोषणा',
    },
    'te': {
      'header': 'మక్తబ్ మేనేజ్మెంట్ — చెల్లింపు రసీదు',
      'date': 'తేదీ',
      'receivedBy': 'స్వీకరించినవారు',
      'student': 'విద్యార్థి',
      'amount': 'మొత్తం',
      'mode': 'పద్ధతి',
      'notes': 'గమనికలు',
      'total': 'మొత్తం',
      'footer': 'జజాక్ అల్లాహ్ ఖైర్.',
      'salaryHeader': 'మక్తబ్ మేనేజ్మెంట్ — జీతం రసీదు',
      'salaryMonth': 'నెల',
      'salaryPaidTo': 'చెల్లించినవారు',
      'salaryIssuedBy': 'జారీ చేసినవారు',
      'attendanceHeader': 'మక్తబ్ మేనేజ్మెంట్ — హాజరు సారాంశం',
      'batch': 'బ్యాచ్',
      'present': 'హాజరు',
      'absent': 'గైర్హాజరు',
      'late': 'ఆలస్యం',
      'leave': 'సెలవు',
      'markedBy': 'గుర్తించినవారు',
      'absentHeader': 'మక్తబ్ మేనేజ్మెంట్ — గైర్హాజరు నోటీసు',
      'absentBody': 'మీ పిల్లవాడు ఈరోజు గైర్హాజరుగా గుర్తించబడ్డారు.',
      'pleaseContact': 'వివరాల కోసం మక్తబ్ను సంప్రదించండి.',
      'batchNoticeHeader': 'మక్తబ్ మేనేజ్మెంట్ — బ్యాచ్ నోటీసు',
      'timing': 'సమయం',
      'announcementHeader': 'మక్తబ్ మేనేజ్మెంట్ — ప్రకటన',
    },
  };

  static Map<String, String> get(String langCode) {
    return _templates[langCode] ?? _templates['en']!;
  }
}
