class ReceiptTemplates {
  static const Map<String, Map<String, String>> _templates = {
    'en': {
      // Fee receipt
      'header': 'Maktab Management — Payment Receipt',
      'date': 'Date',
      'receivedBy': 'Received by',
      'student': 'Student',
      'amount': 'Amount',
      'mode': 'Mode',
      'notes': 'Notes',
      'total': 'Total',
      'footer': 'Jazak Allah Khair.',
      // Salary receipt
      'salaryHeader': 'Salary Receipt',
      'salaryMonth': 'Month',
      'salaryPaidTo': 'Paid to',
      'salaryIssuedBy': 'Issued by',
      // Attendance
      'attendanceHeader': 'Attendance Summary',
      'batch': 'Batch',
      'present': 'Present',
      'absent': 'Absent',
      'late': 'Late',
      'leave': 'Leave',
      'markedBy': 'Marked by',
      // Absent notification
      'absentHeader': 'Maktab Management — Absence Notice',
      'absentBody': 'Your child was marked ABSENT today.',
      'pleaseContact': 'Please contact the Maktab for details.',
      // Batch notice
      'batchNoticeHeader': 'Maktab Management — Batch Notice',
      'timing': 'Timing',
      // Generic announcement
      'announcementHeader': 'Maktab Management — Announcement',

      // --- Task 2: Sabaq keys ---
      'sabaqBismillah': 'بسم الله الرحمن الرحيم',
      'sabaqSalam': 'السلام عليكم ورحمة الله وبركاته',
      'sabaqGreeting': 'Respected Parent/Guardian,',
      'sabaqIntro': "We are pleased to share today's Sabaq progress for your child,",
      'sabaqDetailsHeader': 'Sabaq Details',
      'sabaqSurahLabel': 'Surah',
      'sabaqAyahLabel': 'Ayah',
      'sabaqTypeLabel': 'Type',
      'sabaqGradeLabel': 'Grade',
      'sabaqDateLabel': 'Date',
      'sabaqNoteHeader': "Teacher's Note",
      'sabaqDefaultNote': 'Alhamdulillah, the recitation was completed with focus and care.',
      'sabaqEncouragement': 'We encourage you to review this portion with your child at home and continue the daily revision practice.',
      'sabaqDua': "May Allah bless your child with steadfastness in learning the Qur'an.",
      'sabaqJazak': 'جزاك الله خيرًا',
      'sabaqRegards': 'Warm regards,',
      'sabaqNoSurahSection': "Today's Session",

      // --- Task 2: Fee receipt keys ---
      'feeHeader': 'Payment Receipt',
      'feeAmount': 'Amount',
      'feeMode': 'Payment Mode',
      'feeReceivedBy': 'Received by',
      'feeFor': 'For',
      'feeBalance': 'Balance Due',
      'feeThankYou': 'Jazak Allah Khair for your prompt payment.',
      'feeCombinedHeader': 'Combined Fee Receipt',
      'feeSiblingTotal': 'Total',

      // --- Task 2: Salary receipt keys ---
      'salaryAmount': 'Amount',
      'salaryMode': 'Payment Mode',
      'salaryThankYou': 'Jazak Allah Khair for your service.',

      // --- Task 2: Attendance keys ---
      'attHeader': 'Attendance Summary',
      'attBatch': 'Batch',
      'attPresent': 'Present',
      'attAbsent': 'Absent',
      'attLate': 'Late',
      'attLeave': 'Leave',
      'attMarkedBy': 'Marked by',
      'attAbsentNotice': 'Absence Notice',
      'attAbsentBody': 'Your child was marked absent today.',
      'attPleaseContact': 'Please contact the Maktab for any details.',

      // --- Teacher Attendance keys ---
      'teacherAttHeader': 'Staff Attendance Notice',
      'teacherNameLabel': 'Teacher',
      'attDateLabel': 'Date',
      'attStatusLabel': 'Status',
      'attNoteLabel': 'Remarks',

      // --- Task 2: Common keys ---
      'commonRegards': 'Warm regards,',
      'commonThanks': 'Jazak Allah Khair.',
    },
    'ur': {
      'header': 'مکتب مینجمنٹ — ادائیگی کی رسید',
      'date': 'تاریخ',
      'receivedBy': 'وصول کنندہ',
      'student': 'طالب علم',
      'amount': 'رقم',
      'mode': 'طریقہ',
      'notes': 'نوٹس',
      'total': 'کل',
      'footer': 'جزاک اللہ خیر۔',
      'salaryHeader': 'تنخواہ کی رسید',
      'salaryMonth': 'مہینہ',
      'salaryPaidTo': 'ادا کیا گیا',
      'salaryIssuedBy': 'جاری کنندہ',
      'attendanceHeader': 'حاضری کا خلاصہ',
      'batch': 'بیچ',
      'present': 'حاضر',
      'absent': 'غیر حاضر',
      'late': 'تاخیر',
      'leave': 'رخصت',
      'markedBy': 'نشان زد کرنے والا',
      'absentHeader': 'مکتب مینجمنٹ — غیر حاضری کی اطلاع',
      'absentBody': 'آپ کے بچے کو آج غیر حاضر نشان زد کیا گیا۔',
      'pleaseContact': 'تفصیلات کے لیے مکتب سے رابطہ کریں۔',
      'batchNoticeHeader': 'مکتب مینجمنٹ — بیچ نوٹس',
      'timing': 'وقت',
      'announcementHeader': 'مکتب مینجمنٹ — اعلان',

      // --- Task 2: Sabaq keys ---
      'sabaqBismillah': 'بسم الله الرحمن الرحيم',
      'sabaqSalam': 'السلام عليكم ورحمة الله وبركاته',
      'sabaqGreeting': 'محترم والدین / سرپرست،',
      'sabaqIntro': 'ہمیں آپ کے بچے کی آج کے سبق کی کارکردگی پیش کرتے ہوئے خوشی ہو رہی ہے،',
      'sabaqDetailsHeader': 'سبق کی تفصیلات',
      'sabaqSurahLabel': 'سورۃ',
      'sabaqAyahLabel': 'آیت',
      'sabaqTypeLabel': 'قسم',
      'sabaqGradeLabel': 'درجہ',
      'sabaqDateLabel': 'تاریخ',
      'sabaqNoteHeader': 'استاد کا نوٹ',
      'sabaqDefaultNote': 'الحمد للہ، تلاوت توجہ اور احتیاط کے ساتھ مکمل کی گئی۔',
      'sabaqEncouragement': 'ہم آپ سے گزارش کرتے ہیں کہ گھر پر اپنے بچے کے ساتھ اس حصے کا اعادہ کریں اور روزانہ دہرانے کی مشق جاری رکھیں۔',
      'sabaqDua': 'اللہ تعالی آپ کے بچے کو قرآن کریم سیکھنے میں استقامت عطا فرمائے۔',
      'sabaqJazak': 'جزاك الله خيرًا',
      'sabaqRegards': 'نیک تمناؤں کے ساتھ،',
      'sabaqNoSurahSection': 'آج کا سیشن',

      // --- Task 2: Fee receipt keys ---
      'feeHeader': 'ادائیگی کی رسید',
      'feeAmount': 'رقم',
      'feeMode': 'ادائیگی کا طریقہ',
      'feeReceivedBy': 'وصول کنندہ',
      'feeFor': 'برائے',
      'feeBalance': 'باقی رقم',
      'feeThankYou': 'بروقت ادائیگی کے لیے جزاک اللہ خیر۔',
      'feeCombinedHeader': 'مشترکہ فیس رسید',
      'feeSiblingTotal': 'کل',

      // --- Task 2: Salary receipt keys ---
      'salaryAmount': 'رقم',
      'salaryMode': 'ادائیگی کا طریقہ',
      'salaryThankYou': 'آپ کی خدمات کے لیے جزاک اللہ خیر۔',

      // --- Task 2: Attendance keys ---
      'attHeader': 'حاضری کا خلاصہ',
      'attBatch': 'بیچ',
      'attPresent': 'حاضر',
      'attAbsent': 'غیر حاضر',
      'attLate': 'تاخیر',
      'attLeave': 'رخصت',
      'attMarkedBy': 'نشان زد کرنے والا',
      'attAbsentNotice': 'غیر حاضری کی اطلاع',
      'attAbsentBody': 'آپ کے بچے کو آج غیر حاضر نشان زد کیا گیا۔',
      'attPleaseContact': 'کسی بھی تفصیل کے لیے براہ کرم مکتب سے رابطہ کریں۔',

      // --- Teacher Attendance keys ---
      'teacherAttHeader': 'اسٹاف کی حاضری کی اطلاع',
      'teacherNameLabel': 'استاد',
      'attDateLabel': 'تاریخ',
      'attStatusLabel': 'حالت',
      'attNoteLabel': 'نوٹ',

      // --- Task 2: Common keys ---
      'commonRegards': 'نیک تمناؤں کے ساتھ،',
      'commonThanks': 'جزاک اللہ خیر۔',
    },
    'hi': {
      'header': 'मकतब प्रबंधन — भुगतान रसीद',
      'date': 'तिथि',
      'receivedBy': 'प्राप्तकर्ता',
      'student': 'छात्र',
      'amount': 'राशि',
      'mode': 'माध्यम',
      'notes': 'टिप्पणी',
      'total': 'कुल',
      'footer': 'जज़ाक अल्लाह खैर।',
      'salaryHeader': 'वेतन रसीद',
      'salaryMonth': 'महीना',
      'salaryPaidTo': 'भुगतान किया गया',
      'salaryIssuedBy': 'जारीकर्ता',
      'attendanceHeader': 'उपस्थिति सारांश',
      'batch': 'बैच',
      'present': 'उपस्थित',
      'absent': 'अनुपस्थित',
      'late': 'देर',
      'leave': 'अवकाश',
      'markedBy': 'चिह्नित करने वाला',
      'absentHeader': 'मकतब प्रबंधन — अनुपस्थिति सूचना',
      'absentBody': 'आपके बच्चे को आज अनुपस्थित चिह्नित किया गया।',
      'pleaseContact': 'विवरण के लिए मकतब से संपर्क करें।',
      'batchNoticeHeader': 'मकतब प्रबंधन — बैच सूचना',
      'timing': 'समय',
      'announcementHeader': 'मकतब प्रबंधन — घोषणा',

      // --- Task 2: Sabaq keys ---
      'sabaqBismillah': 'بسم الله الرحمن الرحيم',
      'sabaqSalam': 'السلام عليكم ورحمة الله وبركاته',
      'sabaqGreeting': 'आदरणीय अभिभावक,',
      'sabaqIntro': 'हमें आपके बच्चे की आज की सबक प्रगति साझा करते हुए प्रसन्नता हो रही है,',
      'sabaqDetailsHeader': 'सबक विवरण',
      'sabaqSurahLabel': 'सूरह',
      'sabaqAyahLabel': 'आयत',
      'sabaqTypeLabel': 'प्रकार',
      'sabaqGradeLabel': 'दर्जा',
      'sabaqDateLabel': 'तिथि',
      'sabaqNoteHeader': 'शिक्षक की टिप्पणी',
      'sabaqDefaultNote': 'अलहम्दुलिल्लाह, पाठ ध्यान और सावधानी से पूरा किया गया।',
      'sabaqEncouragement': 'हम आपसे अनुरोध करते हैं कि घर पर अपने बच्चे के साथ इस भाग की समीक्षा करें और दैनिक अभ्यास जारी रखें।',
      'sabaqDua': 'अल्लाह आपके बच्चे को कुरआन सीखने में दृढ़ता प्रदान करे।',
      'sabaqJazak': 'جزاك الله خيرًا',
      'sabaqRegards': 'सादर,',
      'sabaqNoSurahSection': 'आज का सत्र',

      // --- Task 2: Fee receipt keys ---
      'feeHeader': 'भुगतान रसीद',
      'feeAmount': 'राशि',
      'feeMode': 'भुगतान का माध्यम',
      'feeReceivedBy': 'प्राप्तकर्ता',
      'feeFor': 'के लिए',
      'feeBalance': 'शेष देय राशि',
      'feeThankYou': 'समय पर भुगतान के लिए जज़ाक अल्लाह खैर।',
      'feeCombinedHeader': 'संयुक्त शुल्क रसीद',
      'feeSiblingTotal': 'कुल',

      // --- Task 2: Salary receipt keys ---
      'salaryAmount': 'राशि',
      'salaryMode': 'भुगतान माध्यम',
      'salaryThankYou': 'आपकी सेवा के लिए जज़ाक अल्लाह खैर।',

      // --- Task 2: Attendance keys ---
      'attHeader': 'उपस्थिति सारांश',
      'attBatch': 'बैच',
      'attPresent': 'उपस्थित',
      'attAbsent': 'अनुपस्थित',
      'attLate': 'देर',
      'attLeave': 'अवकाश',
      'attMarkedBy': 'चिह्नितकर्ता',
      'attAbsentNotice': 'अनुपस्थिति सूचना',
      'attAbsentBody': 'आपके बच्चे को आज अनुपस्थित दर्ज किया गया है।',
      'attPleaseContact': 'कृपया किसी भी विवरण के लिए मकतब से संपर्क करें।',

      // --- Teacher Attendance keys ---
      'teacherAttHeader': 'स्टाफ उपस्थिति सूचना',
      'teacherNameLabel': 'शिक्षक',
      'attDateLabel': 'तिथि',
      'attStatusLabel': 'स्थिति',
      'attNoteLabel': 'टिप्पणी',

      // --- Task 2: Common keys ---
      'commonRegards': 'सादर,',
      'commonThanks': 'जज़ाक अल्लाह खैर।',
    },
    'te': {
      'header': 'మక్తబ్ మేనేజ్మెంట్ — చెల్లింపు రసీదు',
      'date': 'తేదీ',
      'receivedBy': 'స్వీకరించినవారు',
      'student': 'విద్యార్థి',
      'amount': 'మొత్తం',
      'mode': 'పద్ధతి',
      'notes': 'గమనికలు',
      'total': 'మొత్తం',
      'footer': 'జజాక్ అల్లాహ్ ఖైర్.',
      'salaryHeader': 'జీతం రసీదు',
      'salaryMonth': 'నెల',
      'salaryPaidTo': 'చెల్లించినవారు',
      'salaryIssuedBy': 'జారీ చేసినవారు',
      'attendanceHeader': 'హాజరు సారాంశం',
      'batch': 'బ్యాచ్',
      'present': 'హాజరు',
      'absent': 'గైర్హాజరు',
      'late': 'ఆలస్యం',
      'leave': 'సెలవు',
      'markedBy': 'గుర్తించినవారు',
      'absentHeader': 'మక్తబ్ మేనేజ్మెంట్ — గైర్హాజరు నోటీసు',
      'absentBody': 'మీ పిల్లవాడు ఈరోజు గైర్హాజరుగా గుర్తించబడ్డారు.',
      'pleaseContact': 'వివరాల కోసం మక్తబ్ను సంప్రదించండి.',
      'batchNoticeHeader': 'మక్తబ్ మేనేజ్మెంట్ — బ్యాచ్ నోటీసు',
      'timing': 'సమయం',
      'announcementHeader': 'మక్తబ్ మేనేజ్మెంట్ — ప్రకటన',

      // --- Task 2: Sabaq keys ---
      'sabaqBismillah': 'بسم الله الرحمن الرحيم',
      'sabaqSalam': 'السلام عليكم ورحمة الله وبركاته',
      'sabaqGreeting': 'గౌరవనీయులైన తల్లిదండ్రులు / సంరక్షకులు,',
      'sabaqIntro': 'మీ పిల్లల ఈరోజు సబక్ పురోగతిని పంచుకోవడానికి మేము సంతోషిస్తున్నాము,',
      'sabaqDetailsHeader': 'సబక్ వివరాలు',
      'sabaqSurahLabel': 'సూరా',
      'sabaqAyahLabel': 'ఆయత్',
      'sabaqTypeLabel': 'రకం',
      'sabaqGradeLabel': 'శ్రేణి',
      'sabaqDateLabel': 'తేదీ',
      'sabaqNoteHeader': 'ఉపాధ్యాయుని గమనిక',
      'sabaqDefaultNote': 'అల్హందులిల్లాహ్, పఠనం ఏకాగ్రత మరియు శ్రద్ధతో పూర్తయింది.',
      'sabaqEncouragement': 'ఇంట్లో మీ పిల్లలతో కలిసి ఈ భాగాన్ని పునశ్చరణ చేయాలని మరియు రోజువారీ అభ్యాసాన్ని కొనసాగించాలని మేము కోరుతున్నాము.',
      'sabaqDua': 'ఖురాన్ నేర్చుకోవడంలో అల్లాహ్ మీ బిడ్డకు పట్టుదలని ప్రసాదించుగాక.',
      'sabaqJazak': 'جزاك الله خيرًا',
      'sabaqRegards': 'భవదీయుడు,',
      'sabaqNoSurahSection': 'ఈనాటి సెషన్',

      // --- Task 2: Fee receipt keys ---
      'feeHeader': 'చెల్లింపు రసీదు',
      'feeAmount': 'మొత్తం',
      'feeMode': 'చెల్లింపు విధానం',
      'feeReceivedBy': 'స్వీకరించినవారు',
      'feeFor': 'కొరకు',
      'feeBalance': 'మిగిలిన బకాయి',
      'feeThankYou': 'సకాలంలో చెల్లించినందుకు జజాక్ అల్లాహ్ ఖైర్.',
      'feeCombinedHeader': 'సమిష్టి ఫీజు రసీదు',
      'feeSiblingTotal': 'మొత్తం',

      // --- Task 2: Salary receipt keys ---
      'salaryAmount': 'మొత్తం',
      'salaryMode': 'చెల్లింపు విధానం',
      'salaryThankYou': 'మీ సేవలకు జజాక్ అల్లాహ్ ఖైర్.',

      // --- Task 2: Attendance keys ---
      'attHeader': 'హాజరు సారాంశం',
      'attBatch': 'బ్యాచ్',
      'attPresent': 'హాజరు',
      'attAbsent': 'గైర్హాజరు',
      'attLate': 'ఆలస్యం',
      'attLeave': 'సెలవు',
      'attMarkedBy': 'నమోదు చేసినవారు',
      'attAbsentNotice': 'గైర్హాజరు నోటీసు',
      'attAbsentBody': 'మీ పిల్లవాడు ఈరోజు గైర్హాజరుగా నమోదు చేయబడ్డారు.',
      'attPleaseContact': 'ఏవైనా వివరాల కోసం దయచేసి మక్తబ్ను సంప్రదించండి.',

      // --- Teacher Attendance keys ---
      'teacherAttHeader': 'సిబ్బంది హాజరు నోటీసు',
      'teacherNameLabel': 'ఉపాధ్యాయుడు',
      'attDateLabel': 'తేదీ',
      'attStatusLabel': 'స్థితి',
      'attNoteLabel': 'గమనికలు',

      // --- Task 2: Common keys ---
      'commonRegards': 'భవదీయుడు,',
      'commonThanks': 'జజాక్ అల్లాహ్ ఖైర్.',
    },
  };

  static Map<String, String> get(String langCode) {
    return _templates[langCode] ?? _templates['en']!;
  }
}
